language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t pressureandtime/docker-react -f Dockerfile.dev .


script:
  - docker run pressureandtime/docker-react npm run test -- --coverage
